name: Daily Automatic Update

on:
  schedule:
   # Run every day at 00:00am UTC 
    - cron: "* * * * *"

    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: DAILY AUTOMATIC UPDATE
        run: |
          curl -X POST ${{secrets.DAILY_AUTOMATIC_UPDATE}} --header "x-gatsby-cache: false"